language: python
cache: pip
python:
  - "3.6"
install:
  - echo "Current JAVA_HOME: $JAVA_HOME"
  - echo "Current java -version:"
  - java -version
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y openjdk-8-jdk --no-install-recommends
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  - pip install -r requirements/common.txt && pip install -r requirements/dev.txt
  - set -e
  - mkdir -p -- tests/data/xml/impc tests/data/fixtures
  - curl https://wwwdev.ebi.ac.uk/~federico/rbrc.tar.gz --output tests/data/xml/impc/rbrc.tar.gz
  - cd tests/data/xml/impc && tar -xvzf rbrc.tar.gz && rm rbrc.tar.gz
  - SPARK_VERSION='2.4.3'
  - HADOOP_VERSION='2.7'
  - curl http://apache.mirror.gtcomm.net/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz --output /tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz
  - cd /tmp && tar -xvzf /tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz
  - cd $TRAVIS_BUILD_DIR
env:
    global:
        - SPARK_HOME=/tmp/spark-2.4.3-bin-hadoop2.7
script:
  - pytest tests/jobs/