language: python
cache:
  - pip: true
  - directories:
      - /home/travis/data/
python:
  - "3.7.4"
install:
  - curl https://raw.githubusercontent.com/amoe/travis-polyglot-test/master/jdk_switcher.sh --output jdk_switcher.sh
  - curl https://raw.githubusercontent.com/amoe/travis-polyglot-test/master/custom_path.sh --output custom_path.sh
  - java -version
  - echo $PATH
  - /usr/local/lib/jvm/openjdk11/bin/java -version
  - /usr/bin/java -version
  - source ./jdk_switcher.sh
  - jdk_switcher use openjdk8
  - source ./custom_path.sh
  - export PATH=$(get_filtered_path /usr/local/lib/jvm/openjdk11/bin)
  - java -version
  - pip install -r requirements/common.txt && pip install -r requirements/dev.txt
  - set -e
  - mkdir -p -- $INPUT_PATH/impc $FIXTURES_PATH
  - curl https://wwwdev.ebi.ac.uk/~federico/rbrc.tar.gz --output $INPUT_PATH/impc/rbrc.tar.gz
  - cd  $INPUT_PATH/impc && tar -xvzf rbrc.tar.gz && rm rbrc.tar.gz
  - SPARK_VERSION='2.4.4'
  - HADOOP_VERSION='2.7'
  - curl http://apache.mirror.gtcomm.net/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz --output /tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz
  - cd /tmp && tar -xzvf /tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz
  - cd $TRAVIS_BUILD_DIR
env:
    global:
        - SPARK_HOME=/tmp/spark-2.4.4-bin-hadoop2.7
        - FIXTURES_PATH=/home/travis/data/fixtures/
        - INPUT_PATH=/home/travis/data/xml/
script:
  - pytest tests/jobs/