language: python
python:
  - "3.6"
install:
  - pip install -r requirements/common.txt && pip install -r requirements/dev.txt
  - set -e
  - SPARK_VERSION='2.3.3'
  - HADOOP_VERSION='2.7'
  - curl http://apache.mirror.gtcomm.net/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz --output /tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz
  - cd /tmp && tar -xvzf /tmp/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz

env:
    global:
        - SPARK_HOME=/tmp/spark-2.3.3-bin-hadoop2.7
script:
  - pytest